### ISSUE TITLE
STI class likers return empty results

### ISSUE THREAD

**Issue by arthurccube** [cmer/socialization#29]
Snapshot  inherited Asset

   **Snapshot < Asset**

and 
current_user.toggle_like!(@snapshot)
@snapshot.liked_by?(current_user)

works fine,

but 
@snapshot.likers(User)

always return empty

**Comment by lukerohde** [comment]
I'm having a similar STI issue.  Saves the follower using the table name but retrieves them using the class name.

**Comment by asoap** [comment]
I also seem to be having an issue with STI.  I have Images as a type of Media.  And when I try to retrieve the amount of likes it tries to get the table name from the class Image which doesn't exist.

**Comment by lukerohde** [comment]
I forked it and got it working in my case. But I wasn't sure why the choice to sometimes pick the class name and sometimes pick the table name. It looked deliberate. I'd hoped to test it but wasn't sure how. Even so, I think I sent a pull request but it was a long time ago now. I may not recall correctly.


On 22 Feb 2016, at 1:29 PM, Derek <notifications@github.com<mailto:notifications@github.com>> wrote:


I also seem to be having an issue with STI. I have Images as a type of Media. And when I try to retrieve the amount of likes it tries to get the table name from the class Image which doesn't exist.

**Comment by asoap** [comment]
Sweet.  Good work.  I think I'm just going to roll my own version.  This doesn't look that complicated to implement.
