### ISSUE TITLE
Demo app?

### ISSUE THREAD

**Issue by mandym-webdev** [cmer/socialization#42]
It looks like the demo app was moved?  Is there a new location?  Thanks

**Comment by Borgaard** [comment]
@mandym-webdev Did you ever find a socialization app to use? I saw your Issue posting on Inkwell as well looking for a demo, and I'm in the same boat. Ideally I'd like to use a socialization gem that is more current than this one (which looks great, and if it were updated I'd love to use it!) which was made 2-3 years ago.

**Comment by mandym-webdev** [comment]
I used a mix of other gems and hand rolling.  It's too bad that this isn't supported, it could be great.

**Comment by bodaonline** [comment]
Hi there!
I am also looking for the files for the demo app. Especially the html.erb files from the view folder.
Anyone?

**Comment by bodaonline** [comment]
Also found an anwer on stackoverlow from the author: http://stackoverflow.com/questions/21540701/ruby-on-rails-socialization-gem-setup

**Comment by Borgaard** [comment]
Nice find!

**Comment by bodaonline** [comment]
I figured out how to use likeable with socialization. Will try uploading a demo app tomorrow. Although still don't know how to immediately update the like to unlike with javascript seemlessly so if you could help with that (its not in vysakh's demo either).

**Comment by bodaonline** [comment]
Here it is the demo app *without* authentication and only for *liking* but you'll get the idea. Read the readme! https://github.com/bodaonline/socialization-demo

**Comment by breim** [comment]
I use this gem on many projects.
I would autocomplete @username on type '@' like twitter, its possible ?

**Comment by clementcole** [comment]
heeyyy
