### ISSUE TITLE
How to block users from following other models?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [cmer/socialization#43]
I have two models in my project. One for businesses and one for normal users. How would I be able to give businesses/users the ability to block each other?

**Comment by MatthewHeath** [comment]
Hi, my apologies for not seeing this sooner: I'm rarely on GitHub these days. The code I provided was just something I typed up (adapted from a client project); I don't have a sample application yet (but I _could_ create one).

The best way to understand the structure of the gem is to read the source files for it.

**Comment by RailsCod3rFuture** [comment]
You've done an awesome job with the gem. I just like to be 100% in the know with best practices for it. If you can build a bare-bones sample project. That would be nice. Thank you.

**Comment by MatthewHeath** [comment]
I didn't create this gem :)
