### ISSUE TITLE
ActiveRecord::Relation and `to_a`

### ISSUE THREAD

**Issue by apauly** [cmer/socialization#44]
I noticed that the methods `followables` and `followers` are calling `to_a` on the retrieved relation:
- https://github.com/cmer/socialization/blob/master/lib/socialization/stores/active_record/follow.rb#L69
- https://github.com/cmer/socialization/blob/master/lib/socialization/stores/active_record/follow.rb#L95

Is there a particular reason for this? I'd prefer to not trigger a database query directly in order to modify the relation (e.g. pagination).

**Comment by cmer** [comment]
I forget, but I think this was done for consistency between Redis and ActiveRecord. This is just from memory though, I might be wrong.

**Comment by jtoy** [comment]
that makes sense, but then it breaks rails functionality like with pagination and changing the order :(
