### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by sandelius** [cmer/socialization#46]
Last commit was over a year ago. What's the status?

**Comment by alejorivera** [comment]
Would love to use this gem. Perhaps someone has a fork they plan on maintaining?

**Comment by sandelius** [comment]
@cmer ping

**Comment by cmer** [comment]
Still maintained. We use it in production with many millions of records and it works great. We haven't added anything to it because it does everything we need.

You can use this safely, it works!
