### ISSUE TITLE
Undefined method "Timestamped migration"

### ISSUE THREAD

**Issue by odilson-dev** [cmer/socialization#75]
While generating socialization files
![Annotation 2024-01-26 125924](https://github.com/cmer/socialization/assets/109919684/a87dcdd1-7aea-46eb-b169-03fff7493290)

**Comment by alexanderbahlk** [comment]
I'm getting the issue still with 

`socialization (2.0.1)`

**Comment by ghost** [comment]
What version of Rails are you using, @alexanderbahlk ?
